# Generated by Django 4.1.1 on 2022-09-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familiar',
            new_name='Persona',
        ),
    ]
